[package]
name = "value-trait"
version = "0.1.3"
authors = ["Heinz N. Gies <heinz@licenser.net>"]
edition = "2018"
license = "Apache-2.0/MIT"
description = "Traits to deal with JSONesque values"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itoa = "0.4"
ryu = "1"
halfbrown = "0.1"
float-cmp = "0.6"
simd-lite = { version = "0.1.0", optional = true }
serde_json = { version = "1", optional = true }

[features]
default = []
# Support for 128 bit integers
128bit = []
# Support for ARM NEON SIMD
neon = ["simd-lite"]
# support for various serde values
serde = ["serde_json"]
